event-loop-threads: 8
worker-threads: 50
kafka-messaging:
    enabled: false
http:
    port: 8080
    server-instances: 16
database:
    url: localhost:5432/spring_vertx_template_database
    user: postgres
    password: mysecretpassword
    connection-pool-size: 30
metrics:
    enabled: true
    prometheus:
        enabled: true
        url: /metrics
        port: 8080
